package com.cryptoVerifier;


public enum ErrorCode {
    NO_ERROR,
    QR_NULL_ERROR,
    INVALID_QR_LENGTH,
    STRING_TO_BYTE_ARRAY_PARSING_FAILED,
    QR_COMPARING_ERROR,
    MISSING_CRYPTOGRAPHY_PARAMETER,
    CERTIFICATE_VERIFICATION_FAILED,
    CERTIFICATE_INVALID_ERROR,
    ELEMENT_CANDIDATE_MISMATCH;
}
